services:
  auth:
    volumes:
      - ./auth-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  data:
    volumes:
      - ./data-service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
