-- Realistic seed data generated for development and query-performance testing.
USE content_engine_db;

INSERT INTO users (id, username, email, bio) VALUES
(1, 'ada_codes', 'ada@example.com', 'Backend engineer and algorithm enthusiast.'),
(2, 'kwame_builds', 'kwame@example.com', 'Cloud architect sharing practical lessons.'),
(3, 'lina_designs', 'lina@example.com', 'Product designer focused on accessible systems.'),
(4, 'sam_data', 'sam@example.com', 'Data analyst exploring useful patterns.'),
(5, 'nia_devops', 'nia@example.com', 'DevOps engineer automating reliable delivery.'),
(6, 'omar_security', 'omar@example.com', 'Application security researcher.'),
(7, 'zuri_mobile', 'zuri@example.com', 'Mobile developer building offline-first apps.'),
(8, 'theo_tests', 'theo@example.com', 'Quality engineer who enjoys edge cases.'),
(9, 'mei_frontend', 'mei@example.com', 'Frontend specialist and performance advocate.'),
(10, 'lucas_sql', 'lucas@example.com', 'Database engineer and query tuner.'),
(11, 'amina_ai', 'amina@example.com', 'Machine learning practitioner.'),
(12, 'peter_product', 'peter@example.com', 'Product manager writing about discovery.'),
(13, 'sofia_docs', 'sofia@example.com', 'Technical writer improving developer experience.'),
(14, 'david_networks', 'david@example.com', 'Network engineer explaining protocols.'),
(15, 'ravi_python', 'ravi@example.com', 'Python mentor and open-source contributor.');

INSERT INTO posts (id, title, content, user_id, status) VALUES
(1, 'Designing Clear APIs', 'Practical conventions for predictable endpoints.', 1, 'published'),
(2, 'Async Python in Practice', 'Patterns for concurrent services.', 15, 'published'),
(3, 'A Safer Deployment Checklist', 'A repeatable path from commit to production.', 5, 'published'),
(4, 'Accessible Forms That Work', 'Labels, errors, and keyboard navigation.', 3, 'published'),
(5, 'Understanding Query Plans', 'Reading execution plans before adding indexes.', 10, 'published'),
(6, 'Threat Modeling for Small Teams', 'A lightweight security review workflow.', 6, 'published'),
(7, 'Offline-First Mobile Data', 'Synchronizing local and remote state.', 7, 'draft'),
(8, 'Testing the Unhappy Path', 'Why failure-focused tests find expensive bugs.', 8, 'published'),
(9, 'Frontend Performance Budgets', 'Make speed a measurable product constraint.', 9, 'published'),
(10, 'Useful Product Metrics', 'Choose metrics tied to user outcomes.', 12, 'published'),
(11, 'Writing Setup Guides', 'Help contributors succeed on the first attempt.', 13, 'published'),
(12, 'TCP Without Mystery', 'A visual mental model of reliable transport.', 14, 'draft'),
(13, 'Feature Stores Explained', 'Organizing reusable machine learning inputs.', 11, 'published'),
(14, 'Cloud Cost Guardrails', 'Prevent surprising infrastructure bills.', 2, 'published'),
(15, 'Data Cleaning Habits', 'Small checks that protect analytical results.', 4, 'published'),
(16, 'Pagination Tradeoffs', 'Offset and cursor pagination compared.', 1, 'draft'),
(17, 'Python Type Hints at Scale', 'Using types to improve collaboration.', 15, 'published'),
(18, 'Blue-Green Releases', 'Reducing deployment risk with parallel stacks.', 5, 'published'),
(19, 'Color Is Not Enough', 'Accessible states beyond visual color cues.', 3, 'published'),
(20, 'Composite Index Design', 'Matching index order to query patterns.', 10, 'published'),
(21, 'Secure Session Cookies', 'Practical browser session protections.', 6, 'published'),
(22, 'Mobile Navigation Patterns', 'Designing predictable screen transitions.', 7, 'published'),
(23, 'Contract Testing APIs', 'Catch integration drift before release.', 8, 'draft'),
(24, 'Rendering Strategies', 'Choosing server, static, and client rendering.', 9, 'published'),
(25, 'Interviewing for Outcomes', 'Discovery questions that reveal real needs.', 12, 'published'),
(26, 'Reference Docs That Scale', 'Structures for large API documentation sets.', 13, 'published'),
(27, 'DNS Debugging Notes', 'A methodical approach to name-resolution failures.', 14, 'published'),
(28, 'Evaluating Classifiers', 'Precision, recall, and threshold decisions.', 11, 'draft'),
(29, 'Observability for Small Services', 'Logs, metrics, and traces without overload.', 2, 'published'),
(30, 'Reproducible Analysis', 'Make every result traceable and repeatable.', 4, 'published');

INSERT INTO comments (id, body, user_id, post_id) VALUES
(1, 'The naming examples made this immediately useful.', 2, 1),
(2, 'I would also document error response shapes.', 3, 1),
(3, 'A semaphore example would be a helpful follow-up.', 1, 2),
(4, 'We adopted this checklist for our weekly release.', 8, 3),
(5, 'Keyboard testing uncovered issues our audit missed.', 9, 4),
(6, 'The EXPLAIN comparison clarified the tradeoff.', 4, 5),
(7, 'Starting with assets is a good framing.', 12, 6),
(8, 'Conflict resolution deserves its own article.', 15, 7),
(9, 'Failure-focused fixtures improved our coverage.', 6, 8),
(10, 'Budgets made our performance review objective.', 3, 9),
(11, 'The outcome metric examples were excellent.', 11, 10),
(12, 'A troubleshooting section saves so much time.', 5, 11),
(13, 'The handshake diagram was memorable.', 7, 12),
(14, 'Clear explanation of online and offline features.', 4, 13),
(15, 'Tagging costs by owner worked well for us.', 10, 14),
(16, 'Automated schema checks protect our dashboards.', 2, 15),
(17, 'Cursor examples would help compare consistency.', 12, 16),
(18, 'Gradual typing was key for our migration.', 13, 17),
(19, 'Rollback rehearsal is the step teams skip.', 6, 18),
(20, 'The focus treatment examples are strong.', 9, 19),
(21, 'Column order is often misunderstood.', 1, 20),
(22, 'Rotating sessions after login is essential.', 14, 21),
(23, 'Deep-link behavior is worth testing too.', 8, 22),
(24, 'Provider verification prevented a real outage.', 5, 23),
(25, 'The decision table is a useful summary.', 10, 24),
(26, 'These prompts improved our discovery calls.', 3, 25),
(27, 'Examples alongside schemas reduce ambiguity.', 15, 26),
(28, 'Checking the resolver first saves time.', 2, 27),
(29, 'Threshold selection should follow business cost.', 12, 28),
(30, 'Starting with service-level objectives helps.', 11, 29),
(31, 'Versioning notebooks avoids many surprises.', 13, 30),
(32, 'I shared this API checklist with my team.', 7, 1),
(33, 'Structured concurrency is another useful angle.', 9, 2),
(34, 'We added database migration verification.', 10, 3),
(35, 'Screen-reader testing changed our priorities.', 6, 4),
(36, 'Covering statistics after ANALYZE matters.', 14, 5),
(37, 'The risk ranking keeps reviews focused.', 4, 6),
(38, 'Retry queues made our sync much safer.', 1, 7),
(39, 'Mutation testing exposed weak assertions.', 11, 8),
(40, 'Image budgets were our biggest quick win.', 5, 9);

INSERT INTO tags (id, name) VALUES
(1, 'python'),
(2, 'web-dev'),
(3, 'tutorial'),
(4, 'databases'),
(5, 'devops'),
(6, 'accessibility'),
(7, 'security'),
(8, 'testing'),
(9, 'mobile'),
(10, 'data');

INSERT INTO post_tags (post_id, tag_id) VALUES
(1, 2),
(1, 3),
(2, 1),
(2, 3),
(3, 5),
(3, 8),
(4, 6),
(4, 2),
(5, 4),
(5, 3),
(6, 7),
(7, 9),
(8, 8),
(9, 2),
(10, 10),
(11, 3),
(13, 10),
(14, 5),
(15, 10),
(17, 1),
(18, 5),
(19, 6),
(20, 4),
(21, 7),
(22, 9),
(23, 8),
(24, 2),
(28, 10),
(29, 5),
(30, 10);
